/*
Navicat MySQL Data Transfer

Source Server         : Local
Source Server Version : 50505
Source Host           : localhost:3306
Source Database       : mcmaster

Target Server Type    : MYSQL
Target Server Version : 50505
File Encoding         : 65001

Date: 2017-03-08 06:58:43
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for categories
-- ----------------------------
DROP TABLE IF EXISTS `categories`;
CREATE TABLE `categories` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `parent` varchar(255) DEFAULT NULL,
  `cat_code` varchar(255) DEFAULT NULL,
  `done` varchar(255) DEFAULT NULL,
  `child` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_cat_code` (`cat_code`)
) ENGINE=InnoDB AUTO_INCREMENT=739 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of categories
-- ----------------------------
INSERT INTO `categories` VALUES ('1', 'Fastening &amp; Joining', '', 'Fastening-Joining\n', null, null);
INSERT INTO `categories` VALUES ('2', 'Fasteners', '1', 'Fasteners', null, null);
INSERT INTO `categories` VALUES ('3', ' Screws &amp; Bolts', '2', 'Screws', null, null);
INSERT INTO `categories` VALUES ('4', ' Threaded Rods &amp; Studs', '2', 'Threaded-Rods', null, null);
INSERT INTO `categories` VALUES ('5', ' Eyebolts', '2', 'Eyebolts', null, null);
INSERT INTO `categories` VALUES ('6', ' U-Bolts', '2', 'U-Bolts', null, null);
INSERT INTO `categories` VALUES ('7', ' Nuts', '2', 'Nuts', null, null);
INSERT INTO `categories` VALUES ('8', ' Washers', '2', 'Standard-Washers', null, null);
INSERT INTO `categories` VALUES ('9', ' Shims', '2', 'Shims', null, null);
INSERT INTO `categories` VALUES ('10', ' Helical &amp; Threaded Inserts', '2', 'Threaded-Inserts', null, null);
INSERT INTO `categories` VALUES ('11', ' Spacers &amp; Standoffs', '2', 'Spacers', null, null);
INSERT INTO `categories` VALUES ('12', ' Pins', '2', 'Pins', null, null);
INSERT INTO `categories` VALUES ('13', ' Anchors', '2', 'Standard-Anchors', null, null);
INSERT INTO `categories` VALUES ('14', ' Nails', '2', 'Nails', null, null);
INSERT INTO `categories` VALUES ('15', ' Nailers', '2', 'Nailers', null, null);
INSERT INTO `categories` VALUES ('16', ' Rivets', '2', 'Rivets', null, null);
INSERT INTO `categories` VALUES ('17', ' Rivet Tools', '2', 'Rivet-Installation-Tools', null, null);
INSERT INTO `categories` VALUES ('18', ' Staples', '2', 'Staples', null, null);
INSERT INTO `categories` VALUES ('19', ' Staplers', '2', 'Staplers', null, null);
INSERT INTO `categories` VALUES ('20', ' Key Stock', '2', 'Machine-Keys', null, null);
INSERT INTO `categories` VALUES ('21', ' Retaining Rings', '2', 'Retaining-Rings', null, null);
INSERT INTO `categories` VALUES ('22', ' Cable Ties', '2', 'Cable-Ties', null, null);
INSERT INTO `categories` VALUES ('23', ' Lanyards', '2', 'Lanyards', null, null);
INSERT INTO `categories` VALUES ('24', ' Magnets', '2', 'Magnets', null, null);
INSERT INTO `categories` VALUES ('25', 'Adhesives &amp; Tape', '1', 'Adhesives-amp-Tape', null, null);
INSERT INTO `categories` VALUES ('26', ' Adhesives', '25', 'Adhesives', null, null);
INSERT INTO `categories` VALUES ('27', ' Tape', '25', 'Fastening-Tape', null, null);
INSERT INTO `categories` VALUES ('28', ' Hook &amp; Loop', '25', 'Hook-and-Loop', null, null);
INSERT INTO `categories` VALUES ('29', 'Welding, Brazing &amp; Soldering', '1', 'Welding-Brazing-amp-Soldering', null, null);
INSERT INTO `categories` VALUES ('30', ' Electrodes &amp; Wire', '29', 'Standard-Welding-Electrodes', null, null);
INSERT INTO `categories` VALUES ('31', ' Welders', '29', 'Welders', null, null);
INSERT INTO `categories` VALUES ('32', ' Gas Regulators', '29', 'Welding-Gas-Regulators', null, null);
INSERT INTO `categories` VALUES ('33', ' Welding Gloves', '29', 'Welding-Gloves', null, null);
INSERT INTO `categories` VALUES ('34', ' Welding Helmets &amp; Glasses', '29', 'Welding-Eye-Protectors', null, null);
INSERT INTO `categories` VALUES ('35', ' Protective Screens', '29', 'Protective-Screens', null, null);
INSERT INTO `categories` VALUES ('36', ' Brazing Alloys', '29', 'Brazing-Supplies', null, null);
INSERT INTO `categories` VALUES ('37', ' Torches', '29', 'Torches', null, null);
INSERT INTO `categories` VALUES ('38', ' Solder', '29', 'Solder', null, null);
INSERT INTO `categories` VALUES ('39', ' Soldering Irons', '29', 'Soldering-Irons', null, null);
INSERT INTO `categories` VALUES ('40', ' Melting Pots', '29', 'Melting-Pots', null, null);
INSERT INTO `categories` VALUES ('41', 'Pipe, Tubing, Hose &amp; Fittings', '', 'Pipe-Tubing-Hose-Fittings\n', null, null);
INSERT INTO `categories` VALUES ('42', ' Pipe Fittings &amp; Pipe', '41', 'Standard-Pipe-Fittings', null, null);
INSERT INTO `categories` VALUES ('43', ' Pipe Hangers', '41', 'Pipe-Hangers', null, null);
INSERT INTO `categories` VALUES ('44', ' Pipe Joints', '41', 'Pipe-Joints', null, null);
INSERT INTO `categories` VALUES ('45', ' Pipe &amp; Tube Repair Clamps', '41', 'Pipe-Repair-Clamps', null, null);
INSERT INTO `categories` VALUES ('46', ' Pipe Flange Spreaders', '41', 'Flange-Spreaders', null, null);
INSERT INTO `categories` VALUES ('47', ' Tubing', '41', 'Tubing', null, null);
INSERT INTO `categories` VALUES ('48', ' Tube Fittings', '41', 'Tube-Fittings', null, null);
INSERT INTO `categories` VALUES ('49', ' Tube Cutters', '41', 'Tube-Cutters', null, null);
INSERT INTO `categories` VALUES ('50', ' Tube Flaring Tools', '41', 'Tube-Flaring-Tools', null, null);
INSERT INTO `categories` VALUES ('51', ' Tube Benders', '41', 'Tube-Benders', null, null);
INSERT INTO `categories` VALUES ('52', ' Manifolds', '41', 'Manifolds', null, null);
INSERT INTO `categories` VALUES ('53', ' Hose', '41', 'Hose', null, null);
INSERT INTO `categories` VALUES ('54', ' Hose Fittings', '41', 'Hose-Fittings', null, null);
INSERT INTO `categories` VALUES ('55', ' Hose Nozzles', '41', 'Hose-Nozzles', null, null);
INSERT INTO `categories` VALUES ('56', ' Hose &amp; Tube Clamps', '41', 'Hose-Clamps', null, null);
INSERT INTO `categories` VALUES ('57', ' Hose Reels', '41', 'Hose-Reels', null, null);
INSERT INTO `categories` VALUES ('58', ' Tank Fittings', '41', 'Tank-Fittings', null, null);
INSERT INTO `categories` VALUES ('59', 'Power Transmission', '', 'Power-Transmission\n', null, null);
INSERT INTO `categories` VALUES ('60', 'Rotary Motion', '59', 'Rotary-Motion', null, null);
INSERT INTO `categories` VALUES ('61', ' Bearings', '60', 'Bearings', null, null);
INSERT INTO `categories` VALUES ('62', ' Bushings', '60', 'Bushings', null, null);
INSERT INTO `categories` VALUES ('63', ' Bearing &amp; Gear Pullers', '60', 'Gear-Pullers', null, null);
INSERT INTO `categories` VALUES ('64', ' Bearing Heaters', '60', 'Bearing-Heaters', null, null);
INSERT INTO `categories` VALUES ('65', ' Motors', '60', 'Motors', null, null);
INSERT INTO `categories` VALUES ('66', ' Speed Reducers', '60', 'Speed-Reducers', null, null);
INSERT INTO `categories` VALUES ('67', ' Clutches', '60', 'Clutches', null, null);
INSERT INTO `categories` VALUES ('68', ' Brake &amp; Clutch Lining', '60', 'Brake-Lining', null, null);
INSERT INTO `categories` VALUES ('69', ' Shafts', '60', 'Rotary-Shafts', null, null);
INSERT INTO `categories` VALUES ('70', ' Shaft Couplings', '60', 'Shaft-Couplings', null, null);
INSERT INTO `categories` VALUES ('71', ' Shaft Collars', '60', 'Shaft-Collars', null, null);
INSERT INTO `categories` VALUES ('72', ' U-Joints', '60', 'Universal-Joints', null, null);
INSERT INTO `categories` VALUES ('74', ' Pulleys', '60', 'Pulleys', null, null);
INSERT INTO `categories` VALUES ('75', ' Belts', '60', 'Drive-Belts', null, null);
INSERT INTO `categories` VALUES ('76', ' Belt Gauges', '60', 'Belt-Tension-Gauges', null, null);
INSERT INTO `categories` VALUES ('77', ' Gears', '60', 'Gears', null, null);
INSERT INTO `categories` VALUES ('78', ' Chain', '60', 'Roller-Chain', null, null);
INSERT INTO `categories` VALUES ('79', ' Chain Tools', '60', 'Chain-Tools', null, null);
INSERT INTO `categories` VALUES ('80', ' Chain Tensioners', '60', 'Chain-Tensioners', null, null);
INSERT INTO `categories` VALUES ('81', ' Sprockets', '60', 'Sprockets', null, null);
INSERT INTO `categories` VALUES ('82', ' Drive Rollers', '60', 'Drive-Rollers', null, null);
INSERT INTO `categories` VALUES ('83', ' Track Rollers', '60', 'Track-Rollers', null, null);
INSERT INTO `categories` VALUES ('84', ' Turntables', '60', 'Turntables', null, null);
INSERT INTO `categories` VALUES ('85', 'Linear Motion', '59', 'Linear-Motion', null, null);
INSERT INTO `categories` VALUES ('86', ' Actuators', '85', 'Linear-Motion-Actuators', null, null);
INSERT INTO `categories` VALUES ('87', ' Bearings', '85', 'Linear-Bearings', null, null);
INSERT INTO `categories` VALUES ('88', ' Shafts', '85', 'Linear-Shafts', null, null);
INSERT INTO `categories` VALUES ('90', ' Acme Threaded Rods', '85', 'Acme-Threaded-Rods', null, null);
INSERT INTO `categories` VALUES ('91', ' Shock Absorbers', '85', 'Shock-Absorbers', null, null);
INSERT INTO `categories` VALUES ('92', ' Rod Ends', '85', 'Rod-Ends', null, null);
INSERT INTO `categories` VALUES ('93', ' Springs', '85', 'Springs', null, null);
INSERT INTO `categories` VALUES ('94', 'Hydraulics', '59', 'Hydraulics', null, null);
INSERT INTO `categories` VALUES ('95', ' Pumps', '94', 'Hydraulic-Pumps', null, null);
INSERT INTO `categories` VALUES ('96', ' Valves', '94', 'Hydraulic-Valves', null, null);
INSERT INTO `categories` VALUES ('97', ' Hose', '94', 'Hydraulic-Hose', null, null);
INSERT INTO `categories` VALUES ('98', ' Hose Fittings', '94', 'Hydraulic-Hose-Fittings', null, null);
INSERT INTO `categories` VALUES ('99', ' Filters', '94', 'Hydraulic-Filters', null, null);
INSERT INTO `categories` VALUES ('100', ' Oil', '94', 'Hydraulic-Oil', null, null);
INSERT INTO `categories` VALUES ('101', ' Reservoirs', '94', 'Hydraulic-Reservoirs', null, null);
INSERT INTO `categories` VALUES ('102', 'Pneumatics', '59', 'Pneumatics', null, null);
INSERT INTO `categories` VALUES ('103', ' Compressors', '102', 'Pneumatic-Compressors', null, null);
INSERT INTO `categories` VALUES ('104', ' Tanks', '102', 'Pneumatic-Tanks', null, null);
INSERT INTO `categories` VALUES ('105', ' Air Flow &amp; Pressure Boosters', '102', 'Compressed-Air-Boosters', null, null);
INSERT INTO `categories` VALUES ('106', ' Filter / Regulator / Lubricators (FRLs)', '102', 'FRLs', null, null);
INSERT INTO `categories` VALUES ('107', ' Dryers', '102', 'Pneumatic-Dryers', null, null);
INSERT INTO `categories` VALUES ('108', ' Moisture Separators &amp; Drain Valves', '102', 'Standard-Moisture-Removers', null, null);
INSERT INTO `categories` VALUES ('109', ' Hose', '102', 'Pneumatic-Hose', null, null);
INSERT INTO `categories` VALUES ('110', ' Quick-Disconnect Hose Couplings', '102', 'Quick-Disconnect-Hose-Couplings', null, null);
INSERT INTO `categories` VALUES ('111', ' Valves', '102', 'Pneumatic-Valves', null, null);
INSERT INTO `categories` VALUES ('112', ' Mufflers', '102', 'Pneumatic-Mufflers', null, null);
INSERT INTO `categories` VALUES ('113', ' Pressure Gauges', '102', 'Pressure-Gauges', null, null);
INSERT INTO `categories` VALUES ('114', 'Sealing', '', 'Sealing\n', null, null);
INSERT INTO `categories` VALUES ('115', ' O-Rings', '114', 'O-Rings', null, null);
INSERT INTO `categories` VALUES ('116', ' Compression Packing', '114', 'Compression-Packing', null, null);
INSERT INTO `categories` VALUES ('117', ' Packing Tools', '114', 'Packing-Tools', null, null);
INSERT INTO `categories` VALUES ('118', ' Gaskets', '114', 'Gaskets', null, null);
INSERT INTO `categories` VALUES ('119', ' Mechanical Seals', '114', 'Mechanical-Seals', null, null);
INSERT INTO `categories` VALUES ('120', ' Weather- stripping', '114', 'Door-Weatherstripping', null, null);
INSERT INTO `categories` VALUES ('121', ' Sealants', '114', 'Sealants', null, null);
INSERT INTO `categories` VALUES ('122', 'Flow &amp; Level Control', '', 'Flow-Level-Control\n', null, null);
INSERT INTO `categories` VALUES ('123', 'Flow', '122', 'Flow', null, null);
INSERT INTO `categories` VALUES ('124', ' Pumps', '123', 'Flow-Pumps', null, null);
INSERT INTO `categories` VALUES ('125', ' Valves', '123', 'Flow-Valves', null, null);
INSERT INTO `categories` VALUES ('126', ' Orifices', '123', 'Orifices', null, null);
INSERT INTO `categories` VALUES ('127', ' Switches', '123', 'Flow-Switches', null, null);
INSERT INTO `categories` VALUES ('128', ' Flowmeters', '123', 'Flowmeters', null, null);
INSERT INTO `categories` VALUES ('129', ' Sights', '123', 'Flow-Sights', null, null);
INSERT INTO `categories` VALUES ('130', ' Mixers', '123', 'Mixers', null, null);
INSERT INTO `categories` VALUES ('131', ' Vibrators', '123', 'Vibrators', null, null);
INSERT INTO `categories` VALUES ('132', 'Liquid Level', '122', 'Liquid-Level', null, null);
INSERT INTO `categories` VALUES ('133', ' Switches', '132', 'Liquid-Level-Switches', null, null);
INSERT INTO `categories` VALUES ('134', ' Indicators', '132', 'Standard-Liquid-Level-Indicators', null, null);
INSERT INTO `categories` VALUES ('135', ' Gauges', '132', 'Standard-Liquid-Level-Gauges-and-Transmitters', null, null);
INSERT INTO `categories` VALUES ('136', ' Sights', '132', 'Glass-Sights', null, null);
INSERT INTO `categories` VALUES ('137', ' Floats', '132', 'Floats', null, null);
INSERT INTO `categories` VALUES ('138', 'Pressure &amp; Temperature Control', '', 'Pressure-Temperature-Control\n', null, null);
INSERT INTO `categories` VALUES ('139', 'Pressure', '138', 'Pressure', null, null);
INSERT INTO `categories` VALUES ('141', ' Recorders', '139', 'Pressure-Recorders', null, null);
INSERT INTO `categories` VALUES ('142', ' Switches', '139', 'Pressure-Switches', null, null);
INSERT INTO `categories` VALUES ('143', ' Transducers', '139', 'Pressure-Transducers', null, null);
INSERT INTO `categories` VALUES ('144', ' Regulators', '139', 'Pressure-Regulators', null, null);
INSERT INTO `categories` VALUES ('145', 'Temperature', '138', 'Temperature', null, null);
INSERT INTO `categories` VALUES ('146', ' Thermo- meters', '145', 'Thermometers', null, null);
INSERT INTO `categories` VALUES ('147', ' Recorders', '145', 'Temperature-Recorders', null, null);
INSERT INTO `categories` VALUES ('148', ' Thermo- couples', '145', 'Thermocouples', null, null);
INSERT INTO `categories` VALUES ('149', ' Resistance Temperature Detectors (RTDs)', '145', 'RTDs', null, null);
INSERT INTO `categories` VALUES ('150', ' Switches', '145', 'Temperature-Switches', null, null);
INSERT INTO `categories` VALUES ('151', ' Thermostats', '145', 'Thermostats', null, null);
INSERT INTO `categories` VALUES ('152', ' Controllers', '145', 'Temperature-Controls', null, null);
INSERT INTO `categories` VALUES ('153', ' Heat Exchangers', '145', 'Heat-Exchangers', null, null);
INSERT INTO `categories` VALUES ('154', ' Chillers', '145', 'Water-Chillers', null, null);
INSERT INTO `categories` VALUES ('155', ' Heaters', '145', 'Heaters', null, null);
INSERT INTO `categories` VALUES ('156', 'Filtering', '', 'Filtering\n', null, null);
INSERT INTO `categories` VALUES ('157', ' Cartridges, Bags &amp; Housings', '156', 'Liquid-Filters', null, null);
INSERT INTO `categories` VALUES ('158', ' Strainers', '156', 'Standard-Filtration-Strainers', null, null);
INSERT INTO `categories` VALUES ('159', ' Water Filters', '156', 'Water-Filters', null, null);
INSERT INTO `categories` VALUES ('160', ' Steam Traps', '156', 'Steam-Traps', null, null);
INSERT INTO `categories` VALUES ('162', ' Air Filters', '156', 'Air-Filters', null, null);
INSERT INTO `categories` VALUES ('163', ' Oil Filters &amp; Skimmers', '156', 'Standard-Filtration-Oil-Removers', null, null);
INSERT INTO `categories` VALUES ('164', ' Perforated Sheets', '156', 'Standard-Perforated-Sheets', null, null);
INSERT INTO `categories` VALUES ('165', ' Wire Cloth', '156', 'Wire-Cloth', null, null);
INSERT INTO `categories` VALUES ('166', ' Plastic Mesh', '156', 'Plastic-Mesh', null, null);
INSERT INTO `categories` VALUES ('167', ' Magnetic Separators', '156', 'Magnetic-Separators', null, null);
INSERT INTO `categories` VALUES ('168', ' Sieves', '156', 'Sieves', null, null);
INSERT INTO `categories` VALUES ('169', ' Breather Vents', '156', 'Breather-Vents', null, null);
INSERT INTO `categories` VALUES ('170', ' Mufflers', '156', 'Mufflers', null, null);
INSERT INTO `categories` VALUES ('171', 'Electrical &amp; Lighting', '', 'Electrical-Lighting\n', null, null);
INSERT INTO `categories` VALUES ('172', 'Wiring &amp; Connecting', '171', 'Wiring-amp-Connecting', null, null);
INSERT INTO `categories` VALUES ('173', ' Wire &amp; Cable', '172', 'Standard-Electrical-Wire', null, null);
INSERT INTO `categories` VALUES ('174', ' Plugs &amp; Receptacles', '172', 'Electrical-Plugs-and-Receptacles', null, null);
INSERT INTO `categories` VALUES ('175', ' Extension Cords &amp; Power Strips', '172', 'Extension-Cords', null, null);
INSERT INTO `categories` VALUES ('176', ' Heat-Shrink Tubing', '172', 'Heat-Shrink-Tubing', null, null);
INSERT INTO `categories` VALUES ('177', ' Sleeving', '172', 'Standard-Cable-Sleeving', null, null);
INSERT INTO `categories` VALUES ('178', ' Cord Grips', '172', 'Cord-Grips', null, null);
INSERT INTO `categories` VALUES ('179', ' Electrical Connectors', '172', 'Electrical-Connectors', null, null);
INSERT INTO `categories` VALUES ('180', ' Electrical Tape', '172', 'Electrical-Tape', null, null);
INSERT INTO `categories` VALUES ('181', ' Bonding &amp; Grounding Equipment', '172', 'Bonding-and-Grounding-Equipment', null, null);
INSERT INTO `categories` VALUES ('182', ' Conduit &amp; Fittings', '172', 'Standard-Electrical-Conduit', null, null);
INSERT INTO `categories` VALUES ('183', ' Tube Benders', '172', 'Standard-Tubing-Benders', null, null);
INSERT INTO `categories` VALUES ('184', ' Raceway', '172', 'Electrical-Raceways', null, null);
INSERT INTO `categories` VALUES ('185', ' Cable Carriers', '172', 'Cable-Carriers', null, null);
INSERT INTO `categories` VALUES ('187', ' Enclosures', '172', 'Electrical-Enclosures', null, null);
INSERT INTO `categories` VALUES ('188', ' Outlet Boxes', '172', 'Outlet-Boxes', null, null);
INSERT INTO `categories` VALUES ('189', ' Wire Strippers &amp; Crimpers', '172', 'Electrical-Wire-Tools', null, null);
INSERT INTO `categories` VALUES ('190', ' Cord Reels', '172', 'Cord-Reels', null, null);
INSERT INTO `categories` VALUES ('191', ' Data &amp; Voice Equipment', '172', 'Networking-Equipment', null, null);
INSERT INTO `categories` VALUES ('192', 'Switching &amp; Controlling', '171', 'Switching-amp-Controlling', null, null);
INSERT INTO `categories` VALUES ('193', ' Switches &amp; Relays', '192', 'Electrical-Controls', null, null);
INSERT INTO `categories` VALUES ('194', ' Transformers', '192', 'Voltage-Transformers', null, null);
INSERT INTO `categories` VALUES ('195', ' Circuit Breakers', '192', 'Circuit-Breakers', null, null);
INSERT INTO `categories` VALUES ('196', ' Fuses', '192', 'Fuses', null, null);
INSERT INTO `categories` VALUES ('197', ' Ground Fault Circuit Interrupters (GFCIs)', '192', 'GFCIs', null, null);
INSERT INTO `categories` VALUES ('198', ' Surge Suppressors', '192', 'Surge-Suppressors', null, null);
INSERT INTO `categories` VALUES ('199', 'Motor Maintenance', '171', 'Motor-Maintenance', null, null);
INSERT INTO `categories` VALUES ('200', ' Electric Motors', '199', 'Electric-Motors', null, null);
INSERT INTO `categories` VALUES ('201', ' Motor Controllers', '199', 'Motor-Controls', null, null);
INSERT INTO `categories` VALUES ('202', ' Motor Capacitors &amp; Contactors', '199', 'Motor-Maintenance-Controls', null, null);
INSERT INTO `categories` VALUES ('203', ' Multimeters &amp; Electrical Testers', '199', 'Electrical-Inspectors', null, null);
INSERT INTO `categories` VALUES ('204', ' Dusters &amp; Cleaners', '199', 'Electrical-Contact-Cleaners', null, null);
INSERT INTO `categories` VALUES ('205', 'Power Generating', '171', 'Power-Generating', null, null);
INSERT INTO `categories` VALUES ('206', ' Batteries', '205', 'Batteries', null, null);
INSERT INTO `categories` VALUES ('207', ' Battery Testers, Chargers &amp; Accessories', '205', 'Battery-Accessories', null, null);
INSERT INTO `categories` VALUES ('208', ' Generators', '205', 'Portable-Power-Generators', null, null);
INSERT INTO `categories` VALUES ('209', 'Lighting', '171', 'Lighting', null, null);
INSERT INTO `categories` VALUES ('210', ' Light Bulbs', '209', 'Light-Bulbs', null, null);
INSERT INTO `categories` VALUES ('211', ' Lights', '209', 'Lights', null, null);
INSERT INTO `categories` VALUES ('212', ' Flashlights', '209', 'Flashlights', null, null);
INSERT INTO `categories` VALUES ('213', ' Light Fixtures', '209', 'Light-Fixtures', null, null);
INSERT INTO `categories` VALUES ('214', ' Ballasts', '209', 'Ballasts', null, null);
INSERT INTO `categories` VALUES ('215', ' Lighting Accessories', '209', 'Lighting-Accessories', null, null);
INSERT INTO `categories` VALUES ('216', 'Raw Materials', '', 'Raw-Materials\n', null, null);
INSERT INTO `categories` VALUES ('217', ' Metals', '216', 'Metals', null, null);
INSERT INTO `categories` VALUES ('218', ' Shim Stock', '216', 'Shim-Stock', null, null);
INSERT INTO `categories` VALUES ('219', ' Wire', '216', 'Wire', null, null);
INSERT INTO `categories` VALUES ('221', ' Expanded Metal', '216', 'Expanded-Metal', null, null);
INSERT INTO `categories` VALUES ('222', ' Plastics', '216', 'Plastics', null, null);
INSERT INTO `categories` VALUES ('223', ' Ceramics', '216', 'Ceramics', null, null);
INSERT INTO `categories` VALUES ('224', ' Graphite', '216', 'Graphite', null, null);
INSERT INTO `categories` VALUES ('225', ' Carbon Fiber', '216', 'Carbon-Fiber', null, null);
INSERT INTO `categories` VALUES ('226', ' Casting Compounds', '216', 'Casting-Compounds', null, null);
INSERT INTO `categories` VALUES ('227', ' Rubber', '216', 'Rubber', null, null);
INSERT INTO `categories` VALUES ('228', ' Foam', '216', 'Foam', null, null);
INSERT INTO `categories` VALUES ('229', ' Insulation', '216', 'Thermal-Insulation', null, null);
INSERT INTO `categories` VALUES ('230', ' Glass', '216', 'Glass', null, null);
INSERT INTO `categories` VALUES ('231', ' Wood', '216', 'Wood', null, null);
INSERT INTO `categories` VALUES ('232', ' Fabrics', '216', 'Fabric', null, null);
INSERT INTO `categories` VALUES ('233', ' Felt', '216', 'Felt', null, null);
INSERT INTO `categories` VALUES ('234', 'Fabricating', '', 'Fabricating\n', null, null);
INSERT INTO `categories` VALUES ('235', 'Machining', '234', 'Machining', null, null);
INSERT INTO `categories` VALUES ('236', ' Drill Bits', '235', 'Drill-Bits', null, null);
INSERT INTO `categories` VALUES ('237', ' Drill Bushings', '235', 'Drill-Bushings', null, null);
INSERT INTO `categories` VALUES ('238', ' Drills', '235', 'Hand-Drills', null, null);
INSERT INTO `categories` VALUES ('239', ' Drill Chuck Arbors', '235', 'Drill-Chuck-Arbors', null, null);
INSERT INTO `categories` VALUES ('240', ' Chucks', '235', 'Chucks', null, null);
INSERT INTO `categories` VALUES ('241', ' Collets', '235', 'Collets', null, null);
INSERT INTO `categories` VALUES ('242', ' Countersinks', '235', 'Countersinks', null, null);
INSERT INTO `categories` VALUES ('243', ' Counterbores', '235', 'Counterbores', null, null);
INSERT INTO `categories` VALUES ('244', ' Lathe Tools', '235', 'Standard-Lathe-Bits', null, null);
INSERT INTO `categories` VALUES ('245', ' Carbide Inserts &amp; Holders', '235', 'Carbide-Inserts', null, null);
INSERT INTO `categories` VALUES ('246', ' End Mills', '235', 'End-Mills', null, null);
INSERT INTO `categories` VALUES ('247', ' Milling Cutters', '235', 'Milling-Cutters', null, null);
INSERT INTO `categories` VALUES ('248', ' Reamers', '235', 'Reamers', null, null);
INSERT INTO `categories` VALUES ('249', ' Routers &amp; Bits', '235', 'Standard-Router-Tools', null, null);
INSERT INTO `categories` VALUES ('250', ' Taps', '235', 'Taps', null, null);
INSERT INTO `categories` VALUES ('251', ' Tapping &amp; Threading Tools', '235', 'Tapping-Tools', null, null);
INSERT INTO `categories` VALUES ('252', ' Dies', '235', 'Dies', null, null);
INSERT INTO `categories` VALUES ('253', ' Broaches', '235', 'Broaches', null, null);
INSERT INTO `categories` VALUES ('254', ' Layout Fluid &amp; Scribers', '235', 'Scribing-Tools', null, null);
INSERT INTO `categories` VALUES ('255', 'Forming', '234', 'Forming', null, null);
INSERT INTO `categories` VALUES ('256', ' Presses', '255', 'Die-Presses', null, null);
INSERT INTO `categories` VALUES ('257', ' Sheet Metal Formers', '255', 'Sheet-Metal-Benders', null, null);
INSERT INTO `categories` VALUES ('259', ' Punches', '255', 'Forming-Punches', null, null);
INSERT INTO `categories` VALUES ('260', 'Clamping &amp; Positioning', '234', 'Clamping-amp-Positioning', null, null);
INSERT INTO `categories` VALUES ('261', ' Clamps', '260', 'Standard-Clamps', null, null);
INSERT INTO `categories` VALUES ('262', ' Vises', '260', 'Vises', null, null);
INSERT INTO `categories` VALUES ('264', ' Positioning Arms', '260', 'Positioning-Arms', null, null);
INSERT INTO `categories` VALUES ('265', ' Spring Plungers', '260', 'Spring-Plungers', null, null);
INSERT INTO `categories` VALUES ('266', ' Tool Balancers', '260', 'Tool-Balancers', null, null);
INSERT INTO `categories` VALUES ('267', 'Parts Cleaning &amp; Treating', '234', 'Parts-Cleaning-amp-Treating', null, null);
INSERT INTO `categories` VALUES ('268', ' Parts Washers', '267', 'Parts-Washers', null, null);
INSERT INTO `categories` VALUES ('269', ' Wire Baskets', '267', 'Wire-Baskets', null, null);
INSERT INTO `categories` VALUES ('270', ' Nozzles', '267', 'Parts-Cleaning-Nozzles', null, null);
INSERT INTO `categories` VALUES ('271', ' Blowguns', '267', 'Blowguns', null, null);
INSERT INTO `categories` VALUES ('273', ' Static Eliminating Blowers', '267', 'Static-Control-Blowers', null, null);
INSERT INTO `categories` VALUES ('274', ' Heat Guns &amp; Lamps', '267', 'Parts-Dryers', null, null);
INSERT INTO `categories` VALUES ('275', ' Ovens &amp; Furnaces', '267', 'Ovens', null, null);
INSERT INTO `categories` VALUES ('276', ' Hot Plates', '267', 'Hot-Plates', null, null);
INSERT INTO `categories` VALUES ('278', 'Abrading &amp; Polishing', '', 'Abrading-Polishing\n', null, null);
INSERT INTO `categories` VALUES ('279', 'Sanding, Filing &amp; Grinding', '278', 'Sanding-Filing-amp-Grinding', null, null);
INSERT INTO `categories` VALUES ('280', ' Sanding Abrasives', '279', 'Sanding-Abrasives', null, null);
INSERT INTO `categories` VALUES ('281', ' Sanders', '279', 'Sanders', null, null);
INSERT INTO `categories` VALUES ('282', ' Files', '279', 'Hand-Files', null, null);
INSERT INTO `categories` VALUES ('283', ' Grinding Wheels', '279', 'Grinding-Wheels', null, null);
INSERT INTO `categories` VALUES ('284', ' Grinders', '279', 'Grinders', null, null);
INSERT INTO `categories` VALUES ('285', ' Grinding Bits', '279', 'Grinding-Bits', null, null);
INSERT INTO `categories` VALUES ('286', ' Burs', '279', 'Rotary-Deburring-Tools', null, null);
INSERT INTO `categories` VALUES ('287', ' Deburring Tools', '279', 'Bur-Tools', null, null);
INSERT INTO `categories` VALUES ('288', ' Brushes', '279', 'Brushes', null, null);
INSERT INTO `categories` VALUES ('289', ' Abrasive Blasters', '279', 'Abrasive-Blasters', null, null);
INSERT INTO `categories` VALUES ('290', ' Abrasive Blasting Media', '279', 'Abrasive-Blasting-Media', null, null);
INSERT INTO `categories` VALUES ('291', ' Sharpeners', '279', 'Tool-Sharpeners', null, null);
INSERT INTO `categories` VALUES ('292', 'Polishing', '278', 'Polishing', null, null);
INSERT INTO `categories` VALUES ('293', ' Cylinder Hones', '292', 'Cylinder-Hones', null, null);
INSERT INTO `categories` VALUES ('294', ' Buffing Wheels', '292', 'Buffing-Wheels', null, null);
INSERT INTO `categories` VALUES ('295', ' Polishers', '292', 'Electric-Buffers', null, null);
INSERT INTO `categories` VALUES ('296', ' Lapping &amp; Polishing Compounds', '292', 'Polishing-Compounds', null, null);
INSERT INTO `categories` VALUES ('297', ' Barrel Tumblers', '292', 'Barrel-Tumblers', null, null);
INSERT INTO `categories` VALUES ('298', ' Finishing Media', '292', 'Vibratory-Finishing-Media', null, null);
INSERT INTO `categories` VALUES ('299', 'Sawing &amp; Cutting', '', 'Sawing-Cutting\n', null, null);
INSERT INTO `categories` VALUES ('300', 'Sawing', '299', 'Sawing', null, null);
INSERT INTO `categories` VALUES ('301', ' Reciprocating Saw Blades', '300', 'Reciprocating-Saw-Blades', null, null);
INSERT INTO `categories` VALUES ('302', ' Jigsaw Blades', '300', 'Jigsaw-Blades', null, null);
INSERT INTO `categories` VALUES ('303', ' Handsaw Blades', '300', 'Handsaw-Blades', null, null);
INSERT INTO `categories` VALUES ('304', ' Band Saw Blades', '300', 'Band-Saw-Blades', null, null);
INSERT INTO `categories` VALUES ('305', ' Circular Saw Blades', '300', 'Circular-Saw-Blades', null, null);
INSERT INTO `categories` VALUES ('306', ' Cutoff Wheels', '300', 'Cutoff-Saw-Blades', null, null);
INSERT INTO `categories` VALUES ('307', ' Saws', '300', 'Saws', null, null);
INSERT INTO `categories` VALUES ('308', ' Hole Saws', '300', 'Hole-Saws', null, null);
INSERT INTO `categories` VALUES ('309', 'Cutting', '299', 'Cutting', null, null);
INSERT INTO `categories` VALUES ('310', ' Knives', '309', 'Knives', null, null);
INSERT INTO `categories` VALUES ('311', ' Scalpels', '309', 'Scalpels', null, null);
INSERT INTO `categories` VALUES ('312', ' Scissors', '309', 'Shears', null, null);
INSERT INTO `categories` VALUES ('313', ' Snips', '309', 'Snips', null, null);
INSERT INTO `categories` VALUES ('314', ' Nibblers', '309', 'Nibblers', null, null);
INSERT INTO `categories` VALUES ('315', ' Bolt &amp; Chain Cutters', '309', 'Standard-Bolt-Cutters', null, null);
INSERT INTO `categories` VALUES ('316', ' Scrapers', '309', 'Scrapers', null, null);
INSERT INTO `categories` VALUES ('317', ' Chisels', '309', 'Wood-Chisels', null, null);
INSERT INTO `categories` VALUES ('319', ' Tile Cutters', '309', 'Tile-Cutters', null, null);
INSERT INTO `categories` VALUES ('320', ' Gasket Cutters', '309', 'Gasket-Cutters', null, null);
INSERT INTO `categories` VALUES ('321', ' Drum Deheaders', '309', 'Drum-Deheaders', null, null);
INSERT INTO `categories` VALUES ('322', ' Paper Cutters', '309', 'Paper-Cutters', null, null);
INSERT INTO `categories` VALUES ('323', 'Safety Supplies', '', 'Safety-Supplies\n', null, null);
INSERT INTO `categories` VALUES ('324', 'Personal Protective Equipment', '323', 'Personal-Protective-Equipment', null, null);
INSERT INTO `categories` VALUES ('325', ' Safety Glasses &amp; Face Shields', '324', 'Eye-Protectors', null, null);
INSERT INTO `categories` VALUES ('326', ' Earplugs', '324', 'Earplugs', null, null);
INSERT INTO `categories` VALUES ('327', ' Hard Hats', '324', 'Hard-Hats', null, null);
INSERT INTO `categories` VALUES ('329', ' Harnesses &amp; Lanyards', '324', 'Fall-Protection-Equipment', null, null);
INSERT INTO `categories` VALUES ('330', ' Clothing', '324', 'Clothing', null, null);
INSERT INTO `categories` VALUES ('331', ' Respirators', '324', 'Respirators', null, null);
INSERT INTO `categories` VALUES ('332', 'Protective Equipment', '323', 'Protective-Equipment', null, null);
INSERT INTO `categories` VALUES ('333', ' First-Aid Supplies', '332', 'First-Aid-Supplies', null, null);
INSERT INTO `categories` VALUES ('334', ' Wash Stations', '332', 'Safety-Wash-Stations', null, null);
INSERT INTO `categories` VALUES ('335', ' Fire Extinguishers &amp; Sprinklers', '332', 'Fire-Extinguisher-Products', null, null);
INSERT INTO `categories` VALUES ('336', ' Gas Detectors', '332', 'Gas-Detectors', null, null);
INSERT INTO `categories` VALUES ('337', ' Lockouts', '332', 'Tagout-Lockouts', null, null);
INSERT INTO `categories` VALUES ('338', ' Machine Guards', '332', 'Machine-Guards', null, null);
INSERT INTO `categories` VALUES ('339', ' Traffic Cones &amp; Signs', '332', 'Traffic-Control-Accessories', null, null);
INSERT INTO `categories` VALUES ('340', ' Belt, Chain &amp; Rope Barriers', '332', 'Pedestrian-Controls', null, null);
INSERT INTO `categories` VALUES ('341', ' Safety Railings', '332', 'Guardrails', null, null);
INSERT INTO `categories` VALUES ('343', ' Mirrors', '332', 'Safety-Mirrors', null, null);
INSERT INTO `categories` VALUES ('344', ' Video Surveillance', '332', 'Video-Surveillance', null, null);
INSERT INTO `categories` VALUES ('345', ' Horns, Bells &amp; Alarms', '332', 'Alarms', null, null);
INSERT INTO `categories` VALUES ('346', ' Status-Indicating Lights', '332', 'Standard-Status-Indicating-Lights', null, null);
INSERT INTO `categories` VALUES ('347', ' Warning Lights', '332', 'Standard-Warning-Lights', null, null);
INSERT INTO `categories` VALUES ('348', ' Gloves', '332', 'Gloves', null, null);
INSERT INTO `categories` VALUES ('349', ' Footwear', '332', 'Protective-Shoes', null, null);
INSERT INTO `categories` VALUES ('350', 'Signs', '323', 'Signs', null, null);
INSERT INTO `categories` VALUES ('352', ' Tags', '350', 'Tags', null, null);
INSERT INTO `categories` VALUES ('353', ' Exit Signs', '350', 'Exit-Signs', null, null);
INSERT INTO `categories` VALUES ('354', ' Floor Marking Tape &amp; Paint', '350', 'Floor-Marking-Supplies', null, null);
INSERT INTO `categories` VALUES ('355', 'Pulling &amp; Lifting', '', 'Pulling-Lifting\n', null, null);
INSERT INTO `categories` VALUES ('356', ' Chain', '355', 'Chain', null, null);
INSERT INTO `categories` VALUES ('357', ' Wire Rope', '355', 'Wire-Rope', null, null);
INSERT INTO `categories` VALUES ('358', ' Fibrous Rope', '355', 'Fibrous-Rope', null, null);
INSERT INTO `categories` VALUES ('359', ' Chain &amp; Rope Fittings', '355', 'Chain-and-Rope-Fittings', null, null);
INSERT INTO `categories` VALUES ('360', ' Hooks', '355', 'Rope-Hooks', null, null);
INSERT INTO `categories` VALUES ('361', ' Slings', '355', 'Slings', null, null);
INSERT INTO `categories` VALUES ('362', ' Lifting Magnets', '355', 'Lifting-Magnets', null, null);
INSERT INTO `categories` VALUES ('363', ' Hoist Rings', '355', 'Hoist-Rings', null, null);
INSERT INTO `categories` VALUES ('365', ' Lifting Clamps', '355', 'Lifting-Clamps', null, null);
INSERT INTO `categories` VALUES ('366', ' Hoists', '355', 'Hoists', null, null);
INSERT INTO `categories` VALUES ('367', ' Trolleys', '355', 'Trolleys', null, null);
INSERT INTO `categories` VALUES ('368', ' Winches', '355', 'Winches', null, null);
INSERT INTO `categories` VALUES ('369', ' Cranes', '355', 'Cranes', null, null);
INSERT INTO `categories` VALUES ('370', ' Jacks', '355', 'Lifting-Jacks', null, null);
INSERT INTO `categories` VALUES ('371', ' Pulleys &amp; Blocks', '355', 'Rope-Pulleys', null, null);
INSERT INTO `categories` VALUES ('372', ' Suction Cups', '355', 'Standard-Suction-Cups', null, null);
INSERT INTO `categories` VALUES ('373', ' Vacuum Cups', '355', 'Standard-Vacuum-Cups', null, null);
INSERT INTO `categories` VALUES ('374', 'Material Handling', '', 'Material-Handling\n', null, null);
INSERT INTO `categories` VALUES ('375', ' Conveyors', '374', 'Conveyors', null, null);
INSERT INTO `categories` VALUES ('376', ' Dollies', '374', 'Dollies', null, null);
INSERT INTO `categories` VALUES ('377', ' Pallet Trucks', '374', 'Pallet-Trucks', null, null);
INSERT INTO `categories` VALUES ('378', ' Carts &amp; Trucks', '374', 'Carts', null, null);
INSERT INTO `categories` VALUES ('379', ' Hitches', '374', 'Hitches', null, null);
INSERT INTO `categories` VALUES ('380', ' Casters', '374', 'Standard-Casters', null, null);
INSERT INTO `categories` VALUES ('381', ' Wheels', '374', 'Standard-Wheels', null, null);
INSERT INTO `categories` VALUES ('382', ' Floor Locks', '374', 'Floor-Locks', null, null);
INSERT INTO `categories` VALUES ('384', ' Lift Tables', '374', 'Lift-Tables', null, null);
INSERT INTO `categories` VALUES ('385', ' Drum Handling Equipment', '374', 'Drum-Handlers', null, null);
INSERT INTO `categories` VALUES ('388', ' Ladders', '374', 'Ladders', null, null);
INSERT INTO `categories` VALUES ('389', ' Step Stools', '374', 'Step-Stools', null, null);
INSERT INTO `categories` VALUES ('390', ' Scaffolds', '374', 'Scaffolds', null, null);
INSERT INTO `categories` VALUES ('391', ' Work Platforms', '374', 'Work-Platforms', null, null);
INSERT INTO `categories` VALUES ('392', ' Adjustable Stands', '374', 'Adjustable-Stands', null, null);
INSERT INTO `categories` VALUES ('393', ' Tie Downs', '374', 'Tie-Downs', null, null);
INSERT INTO `categories` VALUES ('394', ' Cycles', '374', 'Cycles', null, null);
INSERT INTO `categories` VALUES ('395', ' Dock Equipment', '374', 'Dock-Equipment', null, null);
INSERT INTO `categories` VALUES ('396', 'Suspending', '', 'Suspending\n', null, null);
INSERT INTO `categories` VALUES ('397', ' Strut Channel', '396', 'Strut-Channel-Systems', null, null);
INSERT INTO `categories` VALUES ('404', ' Beam Clamps', '396', 'Beam-Clamps', null, null);
INSERT INTO `categories` VALUES ('405', ' Turnbuckles', '396', 'Turnbuckles', null, null);
INSERT INTO `categories` VALUES ('406', 'Lubricating', '', 'Lubricating\n', null, null);
INSERT INTO `categories` VALUES ('407', ' Grease', '406', 'Grease', null, null);
INSERT INTO `categories` VALUES ('408', ' Grease Guns', '406', 'Grease-Guns', null, null);
INSERT INTO `categories` VALUES ('409', ' Grease Fittings', '406', 'Grease-Fittings', null, null);
INSERT INTO `categories` VALUES ('410', ' Oil', '406', 'Oil', null, null);
INSERT INTO `categories` VALUES ('411', ' Lubrication Systems', '406', 'Lubrication-Systems', null, null);
INSERT INTO `categories` VALUES ('412', ' Oilers', '406', 'Oilers', null, null);
INSERT INTO `categories` VALUES ('413', ' Lubricants', '406', 'Lubricants', null, null);
INSERT INTO `categories` VALUES ('414', ' Metalworking Fluids', '406', 'Machining-Fluids', null, null);
INSERT INTO `categories` VALUES ('415', ' Coolant Hose &amp; Dispensers', '406', 'Coolant-Systems', null, null);
INSERT INTO `categories` VALUES ('416', 'Hand Tools', '', 'Hand-Tools\n', null, null);
INSERT INTO `categories` VALUES ('417', ' Hammers', '416', 'Hammers', null, null);
INSERT INTO `categories` VALUES ('418', ' Screwdrivers', '416', 'Screwdrivers', null, null);
INSERT INTO `categories` VALUES ('419', ' Wrenches', '416', 'Wrenches', null, null);
INSERT INTO `categories` VALUES ('420', ' Pliers', '416', 'Pliers', null, null);
INSERT INTO `categories` VALUES ('421', ' Sockets', '416', 'Drive-Sockets', null, null);
INSERT INTO `categories` VALUES ('422', ' Nutdrivers', '416', 'Nutdrivers', null, null);
INSERT INTO `categories` VALUES ('423', ' Hex Keys &amp; Drivers', '416', 'Hex-Keys', null, null);
INSERT INTO `categories` VALUES ('425', ' Saws', '416', 'Handsaws', null, null);
INSERT INTO `categories` VALUES ('428', ' Chisels', '416', 'Hand-Chisels', null, null);
INSERT INTO `categories` VALUES ('430', ' Pry Bars', '416', 'Pry-Bars', null, null);
INSERT INTO `categories` VALUES ('431', ' Tweezers', '416', 'Tweezers', null, null);
INSERT INTO `categories` VALUES ('432', ' Screw Extractors', '416', 'Screw-Extractors', null, null);
INSERT INTO `categories` VALUES ('434', ' Nonsparking Tools', '416', 'Nonsparking-Tools', null, null);
INSERT INTO `categories` VALUES ('435', ' Tape Rules', '416', 'Tape-Rules', null, null);
INSERT INTO `categories` VALUES ('436', ' Retrievers &amp; Picks', '416', 'Small-Parts-Positioners', null, null);
INSERT INTO `categories` VALUES ('438', ' Tool Sets', '416', 'Hand-Tool-Sets', null, null);
INSERT INTO `categories` VALUES ('439', 'Measuring &amp; Inspecting', '', 'Measuring-Inspecting\n', null, null);
INSERT INTO `categories` VALUES ('440', 'Dimensional Measuring', '439', 'Dimensional-Measuring', null, null);
INSERT INTO `categories` VALUES ('441', ' Rules', '440', 'Rule-Straightedges', null, null);
INSERT INTO `categories` VALUES ('442', ' Tape Rules', '440', 'Graduated-Tape-Rules', null, null);
INSERT INTO `categories` VALUES ('443', ' Micrometers', '440', 'Micrometers', null, null);
INSERT INTO `categories` VALUES ('444', ' Calipers', '440', 'Calipers', null, null);
INSERT INTO `categories` VALUES ('445', ' Feeler Gauges', '440', 'Feeler-Gauges', null, null);
INSERT INTO `categories` VALUES ('446', ' Height Gauges', '440', 'Height-Gauges', null, null);
INSERT INTO `categories` VALUES ('447', ' Depth Gauges', '440', 'Depth-Gauges', null, null);
INSERT INTO `categories` VALUES ('448', ' Bore Gauges', '440', 'Bore-Gauges', null, null);
INSERT INTO `categories` VALUES ('449', ' Thickness Gauges', '440', 'Surface-Coating-Thickness-Gauges', null, null);
INSERT INTO `categories` VALUES ('450', ' Dial Indicators', '440', 'Test-Indicators', null, null);
INSERT INTO `categories` VALUES ('451', ' Layout Tools', '440', 'Pipe-Layout-Tools', null, null);
INSERT INTO `categories` VALUES ('452', ' Squares &amp; Protractors', '440', 'Standard-Angle-Measurers', null, null);
INSERT INTO `categories` VALUES ('453', ' Levels', '440', 'Levels', null, null);
INSERT INTO `categories` VALUES ('454', ' Compasses', '440', 'Compasses', null, null);
INSERT INTO `categories` VALUES ('455', 'Calibrating', '439', 'Calibrating', null, null);
INSERT INTO `categories` VALUES ('456', ' Gauge Blocks', '455', 'Gauge-Blocks', null, null);
INSERT INTO `categories` VALUES ('457', ' Plug Gauges', '455', 'Plug-Gauges', null, null);
INSERT INTO `categories` VALUES ('458', ' Thread Gauges', '455', 'Thread-Gauges', null, null);
INSERT INTO `categories` VALUES ('459', ' Parallels', '455', 'Parallels', null, null);
INSERT INTO `categories` VALUES ('460', ' Surface Plates', '455', 'Surface-Plates', null, null);
INSERT INTO `categories` VALUES ('461', ' V-Blocks', '455', 'V-Blocks', null, null);
INSERT INTO `categories` VALUES ('464', ' Hydrostatic Pumps', '455', 'Hydrostatic-Test-Pumps', null, null);
INSERT INTO `categories` VALUES ('465', ' Test Weights', '455', 'Test-Weights', null, null);
INSERT INTO `categories` VALUES ('466', 'Inspecting', '439', 'Inspecting', null, null);
INSERT INTO `categories` VALUES ('467', ' Microscopes', '466', 'Microscopes', null, null);
INSERT INTO `categories` VALUES ('468', ' Magnifiers', '466', 'Magnifiers', null, null);
INSERT INTO `categories` VALUES ('469', ' Inspection Mirrors', '466', 'Inspection-Mirrors', null, null);
INSERT INTO `categories` VALUES ('470', ' Flaw Detectors', '466', 'Crack-Detectors', null, null);
INSERT INTO `categories` VALUES ('471', ' Ultraviolet Lights', '466', 'Ultraviolet-Lights', null, null);
INSERT INTO `categories` VALUES ('472', ' Hardness Testers', '466', 'Hardness-Testers', null, null);
INSERT INTO `categories` VALUES ('473', ' Scales', '466', 'Weight-Scales', null, null);
INSERT INTO `categories` VALUES ('474', ' Counters', '466', 'Counter-Totalizers', null, null);
INSERT INTO `categories` VALUES ('475', ' Force Gauges', '466', 'Force-Gauges', null, null);
INSERT INTO `categories` VALUES ('476', ' Water Quality &amp; pH Testers', '466', 'pH-Testers', null, null);
INSERT INTO `categories` VALUES ('477', ' Leak Detectors', '466', 'Leak-Detectors', null, null);
INSERT INTO `categories` VALUES ('479', 'Motion &amp; Speed Measuring', '439', 'Motion-amp-Speed-Measuring', null, null);
INSERT INTO `categories` VALUES ('480', ' Tachometers', '479', 'Tachometers', null, null);
INSERT INTO `categories` VALUES ('481', ' Encoders &amp; Transducers', '479', 'Encoders', null, null);
INSERT INTO `categories` VALUES ('482', ' Stroboscopes', '479', 'Stroboscopes', null, null);
INSERT INTO `categories` VALUES ('483', ' Vibration Meters', '479', 'Vibration-Meters', null, null);
INSERT INTO `categories` VALUES ('484', 'Hardware', '', 'Hardware\n', null, null);
INSERT INTO `categories` VALUES ('485', 'Machinery Hardware', '484', 'Machinery-Hardware', null, null);
INSERT INTO `categories` VALUES ('486', ' Knobs', '485', 'Knobs', null, null);
INSERT INTO `categories` VALUES ('487', ' Hand Wheels', '485', 'Hand-Wheels', null, null);
INSERT INTO `categories` VALUES ('488', ' Handles', '485', 'Machine-Handles', null, null);
INSERT INTO `categories` VALUES ('489', ' Grips', '485', 'Hand-Grips', null, null);
INSERT INTO `categories` VALUES ('490', ' Machinery Mounts', '485', 'Machine-Mounts', null, null);
INSERT INTO `categories` VALUES ('491', ' Glides', '485', 'Floor-Protectors', null, null);
INSERT INTO `categories` VALUES ('492', ' Edge Trim', '485', 'Edge-Trim', null, null);
INSERT INTO `categories` VALUES ('493', ' Bumpers', '485', 'Bumper-Cushions', null, null);
INSERT INTO `categories` VALUES ('494', ' Bellows', '485', 'Bellows', null, null);
INSERT INTO `categories` VALUES ('495', ' Caps &amp; Plugs', '485', 'Standard-Cap-Plugs', null, null);
INSERT INTO `categories` VALUES ('496', ' Control Cables', '485', 'Throttle-Cable', null, null);
INSERT INTO `categories` VALUES ('497', ' Grommets', '485', 'Grommets', null, null);
INSERT INTO `categories` VALUES ('498', 'Door &amp; Cabinet Hardware', '484', 'Door-amp-Cabinet-Hardware', null, null);
INSERT INTO `categories` VALUES ('499', ' Hinges', '498', 'Door-Hinges', null, null);
INSERT INTO `categories` VALUES ('500', ' Door Closers', '498', 'Door-Closers', null, null);
INSERT INTO `categories` VALUES ('501', ' Push Bars', '498', 'Push-Bars', null, null);
INSERT INTO `categories` VALUES ('502', ' Door Holders &amp; Stops', '498', 'Door-Stops', null, null);
INSERT INTO `categories` VALUES ('503', ' Hasps', '498', 'Door-Hasps', null, null);
INSERT INTO `categories` VALUES ('505', ' Door Track &amp; Hangers', '498', 'Door-Hanging-Tracks', null, null);
INSERT INTO `categories` VALUES ('506', ' Magnetic Contacts', '498', 'Magnetic-Door-Contacts', null, null);
INSERT INTO `categories` VALUES ('507', ' Catches', '498', 'Door-Catches', null, null);
INSERT INTO `categories` VALUES ('508', ' Cam Latches', '498', 'Cam-Latches', null, null);
INSERT INTO `categories` VALUES ('509', ' Draw Latches', '498', 'Draw-Latches', null, null);
INSERT INTO `categories` VALUES ('510', ' Slide Bolts', '498', 'Slide-Bolts', null, null);
INSERT INTO `categories` VALUES ('511', ' Pull Handles', '498', 'Pull-Handles', null, null);
INSERT INTO `categories` VALUES ('512', ' Drawer Slides', '498', 'Drawer-Slides', null, null);
INSERT INTO `categories` VALUES ('513', ' Lid Supports', '498', 'Lid-Supports', null, null);
INSERT INTO `categories` VALUES ('514', ' Hooks', '498', 'Door-Hooks', null, null);
INSERT INTO `categories` VALUES ('515', ' Brackets', '498', 'Corner-Brackets', null, null);
INSERT INTO `categories` VALUES ('516', ' Window Hardware', '498', 'Window-Hardware', null, null);
INSERT INTO `categories` VALUES ('517', 'Locks', '484', 'Locks', null, null);
INSERT INTO `categories` VALUES ('518', ' Door Locks', '517', 'Door-Locks', null, null);
INSERT INTO `categories` VALUES ('519', ' Deadbolt Locks', '517', 'Deadbolt-Locks', null, null);
INSERT INTO `categories` VALUES ('520', ' Drawer Locks', '517', 'Drawer-Locks', null, null);
INSERT INTO `categories` VALUES ('521', ' Padlocks', '517', 'Padlocks', null, null);
INSERT INTO `categories` VALUES ('523', ' Key Holders', '517', 'Key-Holders', null, null);
INSERT INTO `categories` VALUES ('524', 'Doors', '484', 'Doors', null, null);
INSERT INTO `categories` VALUES ('525', ' Doors', '524', 'Standard-Doors', null, null);
INSERT INTO `categories` VALUES ('526', ' Vinyl Strip Doors', '524', 'Vinyl-Strip-Doors', null, null);
INSERT INTO `categories` VALUES ('527', ' Folding Gates', '524', 'Folding-Gates', null, null);
INSERT INTO `categories` VALUES ('528', ' Air Curtains', '524', 'Air-Curtains', null, null);
INSERT INTO `categories` VALUES ('529', 'Furniture &amp; Storage', '', 'Furniture-Storage\n', null, null);
INSERT INTO `categories` VALUES ('530', 'Furniture', '529', 'Furniture', null, null);
INSERT INTO `categories` VALUES ('531', ' Tables', '530', 'Office-Tables', null, null);
INSERT INTO `categories` VALUES ('532', ' Workstations &amp; Desks', '530', 'Workstations', null, null);
INSERT INTO `categories` VALUES ('533', ' Workbenches', '530', 'Workbenches', null, null);
INSERT INTO `categories` VALUES ('534', ' Framing &amp; Railing Components', '530', 'Structural-Framing', null, null);
INSERT INTO `categories` VALUES ('535', ' Benches', '530', 'Bench-Seating', null, null);
INSERT INTO `categories` VALUES ('536', ' Stools &amp; Seats', '530', 'Task-Stools', null, null);
INSERT INTO `categories` VALUES ('537', ' Chairs', '530', 'Chairs', null, null);
INSERT INTO `categories` VALUES ('538', 'Storage', '529', 'Storage', null, null);
INSERT INTO `categories` VALUES ('539', ' Cabinets', '538', 'Storage-Cabinets', null, null);
INSERT INTO `categories` VALUES ('540', ' Lockers', '538', 'Lockers', null, null);
INSERT INTO `categories` VALUES ('541', ' Coat Racks', '538', 'Coat-Racks', null, null);
INSERT INTO `categories` VALUES ('542', ' Shelving', '538', 'Storage-Shelving', null, null);
INSERT INTO `categories` VALUES ('543', ' Racks', '538', 'Storage-Racks', null, null);
INSERT INTO `categories` VALUES ('544', ' Pallets', '538', 'Pallets', null, null);
INSERT INTO `categories` VALUES ('545', ' Chests', '538', 'Storage-Chests', null, null);
INSERT INTO `categories` VALUES ('546', ' Storage Buildings', '538', 'Storage-Buildings', null, null);
INSERT INTO `categories` VALUES ('547', ' Partitions', '538', 'Partitions', null, null);
INSERT INTO `categories` VALUES ('548', ' Tool Holders', '538', 'Tool-Holders', null, null);
INSERT INTO `categories` VALUES ('550', 'Containers', '529', 'Containers', null, null);
INSERT INTO `categories` VALUES ('551', ' Jars, Bottles &amp; Pitchers', '550', 'Liquid-Containers', null, null);
INSERT INTO `categories` VALUES ('552', ' Pails', '550', 'Pails', null, null);
INSERT INTO `categories` VALUES ('553', ' Tanks', '550', 'Storage-Tanks', null, null);
INSERT INTO `categories` VALUES ('554', ' Drums', '550', 'Drums', null, null);
INSERT INTO `categories` VALUES ('555', ' Fuel &amp; Safety Cans', '550', 'Flammable-Liquids-Cans', null, null);
INSERT INTO `categories` VALUES ('556', ' Sprayers', '550', 'Spray-Containers', null, null);
INSERT INTO `categories` VALUES ('557', ' Spill Control Containers', '550', 'Spill-Control-Containers', null, null);
INSERT INTO `categories` VALUES ('558', ' Boxes', '550', 'Storage-Boxes', null, null);
INSERT INTO `categories` VALUES ('559', ' Pans', '550', 'Pans', null, null);
INSERT INTO `categories` VALUES ('560', ' Dump Trucks', '550', 'Dump-Trucks', null, null);
INSERT INTO `categories` VALUES ('561', ' Waste Containers', '550', 'Waste-Containers', null, null);
INSERT INTO `categories` VALUES ('562', ' Garbage Bags', '550', 'Garbage-Bags', null, null);
INSERT INTO `categories` VALUES ('563', ' Funnels &amp; Scoops', '550', 'Standard-Material-Routers', null, null);
INSERT INTO `categories` VALUES ('565', 'Plumbing &amp; Janitorial', '', 'Plumbing-Janitorial\n', null, null);
INSERT INTO `categories` VALUES ('566', ' Faucets &amp; Showers', '565', 'Water-Faucets', null, null);
INSERT INTO `categories` VALUES ('567', ' Sinks &amp; Wash Fountains', '565', 'Sinks', null, null);
INSERT INTO `categories` VALUES ('568', ' Drinking Fountains', '565', 'Drinking-Fountains', null, null);
INSERT INTO `categories` VALUES ('569', ' Toilets &amp; Urinals', '565', 'Toilets', null, null);
INSERT INTO `categories` VALUES ('570', ' Plungers &amp; Drain Cleaners', '565', 'Drain-Cleaners', null, null);
INSERT INTO `categories` VALUES ('571', ' Test Pumps, Plugs &amp; Fittings', '565', 'Test-Pumps-and-Plugs', null, null);
INSERT INTO `categories` VALUES ('572', ' Privacy Partitions', '565', 'Lavatory-Privacy-Partitions', null, null);
INSERT INTO `categories` VALUES ('573', ' Lavatory Mirrors &amp; Fixtures', '565', 'Standard-Lavatory-Fixtures', null, null);
INSERT INTO `categories` VALUES ('574', ' Personal Care Products', '565', 'Feminine-Hygiene-Products', null, null);
INSERT INTO `categories` VALUES ('575', ' Paper Towels &amp; Dispensers', '565', 'Standard-Paper-Towel-Dispensers', null, null);
INSERT INTO `categories` VALUES ('576', ' Dryers', '565', 'Lavatory-Dryers', null, null);
INSERT INTO `categories` VALUES ('577', ' Hand Cleaners', '565', 'Standard-Hand-Cleaners', null, null);
INSERT INTO `categories` VALUES ('578', ' Cleaners &amp; Deodorizers', '565', 'Standard-Cleaners', null, null);
INSERT INTO `categories` VALUES ('579', ' Tissues, Towels &amp; Wipes', '565', 'Cleaning-Wipes', null, null);
INSERT INTO `categories` VALUES ('580', ' Sponges &amp; Brushes', '565', 'Standard-Cleaning-Hand-Tools', null, null);
INSERT INTO `categories` VALUES ('582', ' Brooms, Mops &amp; Squeegees', '565', 'Floor-Cleaning-Tools', null, null);
INSERT INTO `categories` VALUES ('583', ' Vacuums', '565', 'Vacuums', null, null);
INSERT INTO `categories` VALUES ('584', ' Floor &amp; Carpet Cleaners', '565', 'Floor-Cleaning-Machines', null, null);
INSERT INTO `categories` VALUES ('585', ' Pressure Washers &amp; Steam Cleaners', '565', 'Power-Washing-Equipment', null, null);
INSERT INTO `categories` VALUES ('586', ' Wash Guns &amp; Spray Nozzles', '565', 'Spray-Nozzles', null, null);
INSERT INTO `categories` VALUES ('587', ' Sorbents', '565', 'Spill-Control-Sorbents', null, null);
INSERT INTO `categories` VALUES ('588', 'Heating &amp; Cooling', '', 'Heating-Cooling\n', null, null);
INSERT INTO `categories` VALUES ('589', ' Heaters', '588', 'Space-Heaters', null, null);
INSERT INTO `categories` VALUES ('590', ' Blowers', '588', 'Standard-Blower-Fans', null, null);
INSERT INTO `categories` VALUES ('591', ' Roof Ventilators', '588', 'Roof-Mount-Ventilators', null, null);
INSERT INTO `categories` VALUES ('592', ' Fume Exhausters &amp; Air Cleaners', '588', 'Air-Cleaners', null, null);
INSERT INTO `categories` VALUES ('593', ' Dust Collectors', '588', 'Dust-Collectors', null, null);
INSERT INTO `categories` VALUES ('594', ' Fans', '588', 'Ventilation-Fans', null, null);
INSERT INTO `categories` VALUES ('595', ' Equipment Cooling Fans', '588', 'Equipment-Cooling-Fans', null, null);
INSERT INTO `categories` VALUES ('596', ' Louvers', '588', 'Louvers', null, null);
INSERT INTO `categories` VALUES ('597', ' Air Conditioners', '588', 'Air-Conditioners', null, null);
INSERT INTO `categories` VALUES ('598', ' Humidifiers &amp; Dehumidifiers', '588', 'Humidity-Control-Machines', null, null);
INSERT INTO `categories` VALUES ('599', ' Desiccants', '588', 'Desiccants', null, null);
INSERT INTO `categories` VALUES ('600', ' Duct &amp; Fittings', '588', 'Duct-Fittings', null, null);
INSERT INTO `categories` VALUES ('601', ' Duct Tape', '588', 'Duct-Tape', null, null);
INSERT INTO `categories` VALUES ('602', ' Air Filters', '588', 'HVAC-Air-Filters', null, null);
INSERT INTO `categories` VALUES ('605', 'Building &amp; Grounds', '', 'Building-Grounds\n', null, null);
INSERT INTO `categories` VALUES ('606', ' Flags', '605', 'Flags', null, null);
INSERT INTO `categories` VALUES ('607', ' Weather Instruments', '605', 'Weather-Instruments', null, null);
INSERT INTO `categories` VALUES ('608', ' Shovels', '605', 'Shovels', null, null);
INSERT INTO `categories` VALUES ('609', ' Landscaping Equipment', '605', 'Landscaping-Equipment', null, null);
INSERT INTO `categories` VALUES ('610', ' Garden Hose', '605', 'Garden-Hose', null, null);
INSERT INTO `categories` VALUES ('611', ' Concrete, Asphalt &amp; Roof Repair', '605', 'Surface-Repair-Products', null, null);
INSERT INTO `categories` VALUES ('612', ' Matting', '605', 'Floor-Mats', null, null);
INSERT INTO `categories` VALUES ('613', ' Tarps', '605', 'Tarps', null, null);
INSERT INTO `categories` VALUES ('614', ' Window Screening &amp; Shades', '605', 'Window-Covers', null, null);
INSERT INTO `categories` VALUES ('615', ' Paint &amp; Coatings', '605', 'Paint', null, null);
INSERT INTO `categories` VALUES ('616', ' Paint Brushes &amp; Sprayers', '605', 'Paint-Applicators', null, null);
INSERT INTO `categories` VALUES ('617', ' Grating &amp; Stair Treads', '605', 'Standard-Stair-Grippers', null, null);
INSERT INTO `categories` VALUES ('622', ' Pest Control', '605', 'Pest-Control-Products', null, null);
INSERT INTO `categories` VALUES ('625', 'Shipping', '', 'Shipping\n', null, null);
INSERT INTO `categories` VALUES ('626', ' Bags &amp; Envelopes', '625', 'Shipping-Bags', null, null);
INSERT INTO `categories` VALUES ('627', ' Tubes', '625', 'Shipping-Tubes', null, null);
INSERT INTO `categories` VALUES ('628', ' Boxes', '625', 'Shipping-Boxes', null, null);
INSERT INTO `categories` VALUES ('629', ' Drums &amp; Pails', '625', 'Shipping-Drums', null, null);
INSERT INTO `categories` VALUES ('630', ' Packing Material', '625', 'Standard-Packing-Material', null, null);
INSERT INTO `categories` VALUES ('631', ' Stretch &amp; Shrink Wrap', '625', 'Stretch-Wrap', null, null);
INSERT INTO `categories` VALUES ('632', ' Strapping &amp; Strapping Tools', '625', 'Strapping-Components', null, null);
INSERT INTO `categories` VALUES ('633', ' Tape', '625', 'Shipping-Tape', null, null);
INSERT INTO `categories` VALUES ('634', ' Tape Dispensers', '625', 'Tape-Dispensers', null, null);
INSERT INTO `categories` VALUES ('635', ' Labels', '625', 'Shipping-Labels', null, null);
INSERT INTO `categories` VALUES ('636', ' Tags', '625', 'Shipping-Tags', null, null);
INSERT INTO `categories` VALUES ('637', ' Security Seals', '625', 'Security-Seals', null, null);
INSERT INTO `categories` VALUES ('638', ' Pallets', '625', 'Shipping-Pallets', null, null);
INSERT INTO `categories` VALUES ('639', ' Scales', '625', 'Shipping-Scales', null, null);
INSERT INTO `categories` VALUES ('641', 'Office Supplies &amp; Signs', '', 'Office-Supplies-Signs\n', null, null);
INSERT INTO `categories` VALUES ('642', 'Office Supplies', '641', 'Office-Supplies', null, null);
INSERT INTO `categories` VALUES ('643', ' Markers, Pens &amp; Pencils', '642', 'Writing-Utensils', null, null);
INSERT INTO `categories` VALUES ('644', ' Clipboards &amp; Binders', '642', 'Hand-Held-File-Holders', null, null);
INSERT INTO `categories` VALUES ('645', ' Folders &amp; Paper', '642', 'Paper-Products', null, null);
INSERT INTO `categories` VALUES ('646', ' Organizers &amp; Document Holders', '642', 'Document-Holders', null, null);
INSERT INTO `categories` VALUES ('647', ' Telephones', '642', 'Telephones', null, null);
INSERT INTO `categories` VALUES ('648', ' Intercoms &amp; Radios', '642', 'Communication-Systems', null, null);
INSERT INTO `categories` VALUES ('649', ' Speakers', '642', 'Speakers', null, null);
INSERT INTO `categories` VALUES ('651', ' Computer Accessories', '642', 'Standard-Computer-Accessories', null, null);
INSERT INTO `categories` VALUES ('652', ' Calculators', '642', 'Calculators', null, null);
INSERT INTO `categories` VALUES ('653', ' Drafting Equipment', '642', 'Drafting-Equipment', null, null);
INSERT INTO `categories` VALUES ('654', ' Clocks &amp; Timers', '642', 'Clocks', null, null);
INSERT INTO `categories` VALUES ('655', ' Reference Books', '642', 'Reference-Books', null, null);
INSERT INTO `categories` VALUES ('656', ' Food Service Equipment', '642', 'Food-Service-Equipment', null, null);
INSERT INTO `categories` VALUES ('659', ' Sign Holders', '350', 'Sign-Holders', null, null);
INSERT INTO `categories` VALUES ('662', ' Laminators', '350', 'Laminators', null, null);
INSERT INTO `categories` VALUES ('663', ' Message &amp; Bulletin Boards', '350', 'Display-Boards', null, null);
INSERT INTO `categories` VALUES ('664', 'Identification &amp; Marking', '641', 'Identification-amp-Marking', null, null);
INSERT INTO `categories` VALUES ('666', ' Labels', '664', 'Adhesive-Backed-Labels', null, null);
INSERT INTO `categories` VALUES ('667', ' Label Printers', '664', 'Label-Printers', null, null);
INSERT INTO `categories` VALUES ('668', ' Stencils &amp; Characters', '664', 'Standard-Marking-Characters', null, null);
INSERT INTO `categories` VALUES ('669', ' Hand Stamps', '664', 'Hand-Stamps', null, null);
INSERT INTO `categories` VALUES ('670', ' Engraving Plates &amp; Tags', '664', 'Engraving-Tags', null, null);
INSERT INTO `categories` VALUES ('671', ' Engravers', '664', 'Engravers', null, null);
INSERT INTO `categories` VALUES ('672', 'Screw-In  Hooks ', '3', 'Screw-In  Hooks ', null, null);
INSERT INTO `categories` VALUES ('673', 'Oversized Steel Machine Key Stock ', '20', 'Oversized-Steel-Machine-Key-Stock-', null, 'yes');
INSERT INTO `categories` VALUES ('675', 'Undersized Steel Machine Key Stock', '20', 'Undersized-Steel-Machine-Key-Stock', null, 'yes');
INSERT INTO `categories` VALUES ('700', 'Standard Socket Head Screws', '2', 'Standard-Socket-Head-Screws', null, 'yes');
INSERT INTO `categories` VALUES ('701', 'Alloy Steel Socket Head Screws ', '700', 'Alloy-Steel-Socket-Head-Screws-', null, 'yes');
INSERT INTO `categories` VALUES ('705', 'Standard Flat Head Screws', '2', 'Standard-Flat-Head-Screws', null, 'yes');
INSERT INTO `categories` VALUES ('706', 'Alloy Steel Hex Drive Flat Head Screws ', '705', 'Alloy-Steel-Hex-Drive-Flat-Head-Screws-', null, 'yes');
INSERT INTO `categories` VALUES ('709', 'Metric Alloy Steel Socket Head Screws ', '700', 'Metric-Alloy-Steel-Socket-Head-Screws-', null, 'yes');

-- ----------------------------
-- Table structure for filters
-- ----------------------------
DROP TABLE IF EXISTS `filters`;
CREATE TABLE `filters` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `value` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=147 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of filters
-- ----------------------------
INSERT INTO `filters` VALUES ('1', 'Zinc-Plated Steel', 'Material');
INSERT INTO `filters` VALUES ('2', '1/16 \" Ã— 1/16 \"', 'Size');
INSERT INTO `filters` VALUES ('3', '12\"', 'Length');
INSERT INTO `filters` VALUES ('4', 'Oversized', 'Tolerance Rating');
INSERT INTO `filters` VALUES ('5', 'Not Rated', 'Minimum Hardness');
INSERT INTO `filters` VALUES ('6', 'Straight', 'Key Type');
INSERT INTO `filters` VALUES ('7', 'Inch', 'System of Measurement');
INSERT INTO `filters` VALUES ('8', 'Compliant', 'RoHS');
INSERT INTO `filters` VALUES ('9', '3/32 \" Ã— 3/32 \"', 'Size');
INSERT INTO `filters` VALUES ('10', '7/64 \" Ã— 7/64 \"', 'Size');
INSERT INTO `filters` VALUES ('11', '1/8 \" Ã— 1/8 \"', 'Size');
INSERT INTO `filters` VALUES ('12', '1/8 \" Ã— 3/16 \"', 'Size');
INSERT INTO `filters` VALUES ('13', '1/8 \" Ã— 1/4 \"', 'Size');
INSERT INTO `filters` VALUES ('14', '1/8 \" Ã— 3/8 \"', 'Size');
INSERT INTO `filters` VALUES ('15', '1/8 \" Ã— 1/2 \"', 'Size');
INSERT INTO `filters` VALUES ('16', '1/8 \" Ã— 5/8 \"', 'Size');
INSERT INTO `filters` VALUES ('17', '1/8 \" Ã— 3/4 \"', 'Size');
INSERT INTO `filters` VALUES ('18', 'M1.4', 'Thread Size');
INSERT INTO `filters` VALUES ('19', '0.3 mm', 'Thread Pitch');
INSERT INTO `filters` VALUES ('20', '3 mm', 'Length');
INSERT INTO `filters` VALUES ('21', 'Fully Threaded', 'Threading');
INSERT INTO `filters` VALUES ('22', '2.5 mm', 'Head Diameter');
INSERT INTO `filters` VALUES ('23', '1.4 mm', 'Head Height');
INSERT INTO `filters` VALUES ('24', '1.3 mm', 'Drive Size');
INSERT INTO `filters` VALUES ('25', 'Black-Oxide Alloy Steel', 'Material');
INSERT INTO `filters` VALUES ('26', 'Class 12.9', 'Fastener Strength Grade/Class');
INSERT INTO `filters` VALUES ('27', 'Rockwell C37', 'Hardness');
INSERT INTO `filters` VALUES ('28', '170,000 psi', 'Tensile Strength');
INSERT INTO `filters` VALUES ('29', 'Metric', 'Thread Type');
INSERT INTO `filters` VALUES ('30', 'Coarse', 'Thread Spacing');
INSERT INTO `filters` VALUES ('31', 'Class 5g6g', 'Thread Fit');
INSERT INTO `filters` VALUES ('32', 'Right Hand', 'Thread Direction');
INSERT INTO `filters` VALUES ('33', 'Socket', 'Head Type');
INSERT INTO `filters` VALUES ('34', 'Standard', 'Socket Head Profile');
INSERT INTO `filters` VALUES ('35', 'Hex', 'Drive Style');
INSERT INTO `filters` VALUES ('36', 'DIN 912, ISO 4762', 'Specifications Met');
INSERT INTO `filters` VALUES ('37', 'Metric', 'System of Measurement');
INSERT INTO `filters` VALUES ('38', '4 mm', 'Length');
INSERT INTO `filters` VALUES ('39', '5 mm', 'Length');
INSERT INTO `filters` VALUES ('40', '6 mm', 'Length');
INSERT INTO `filters` VALUES ('41', 'M1.6', 'Thread Size');
INSERT INTO `filters` VALUES ('42', '0.35 mm', 'Thread Pitch');
INSERT INTO `filters` VALUES ('43', '3 mm', 'Head Diameter');
INSERT INTO `filters` VALUES ('44', '1.6 mm', 'Head Height');
INSERT INTO `filters` VALUES ('45', '1.5 mm', 'Drive Size');
INSERT INTO `filters` VALUES ('46', '8 mm', 'Length');
INSERT INTO `filters` VALUES ('47', '12 mm', 'Length');
INSERT INTO `filters` VALUES ('48', '0-80', 'Thread Size');
INSERT INTO `filters` VALUES ('49', '1/16 \"', 'Length ');
INSERT INTO `filters` VALUES ('50', '0.096\"', 'Head Diameter ');
INSERT INTO `filters` VALUES ('51', '0.06\"', 'Head Height ');
INSERT INTO `filters` VALUES ('52', '3/64 \"', 'Drive Size');
INSERT INTO `filters` VALUES ('53', '0.060\"', 'Screw Size Decimal Equivalent');
INSERT INTO `filters` VALUES ('54', 'UNF', 'Thread Type');
INSERT INTO `filters` VALUES ('55', 'Fine', 'Thread Spacing');
INSERT INTO `filters` VALUES ('56', 'Class 3A', 'Thread Fit');
INSERT INTO `filters` VALUES ('57', 'ASTM A574', 'Specifications Met');
INSERT INTO `filters` VALUES ('58', '3/32 \"', 'Length ');
INSERT INTO `filters` VALUES ('59', '1/8 \"', 'Length ');
INSERT INTO `filters` VALUES ('60', '5/32 \"', 'Length ');
INSERT INTO `filters` VALUES ('61', '3/16 \"', 'Length ');
INSERT INTO `filters` VALUES ('62', '1/4 \"', 'Length ');
INSERT INTO `filters` VALUES ('63', '5/16 \"', 'Length ');
INSERT INTO `filters` VALUES ('64', 'Standard', 'Flat Head Profile');
INSERT INTO `filters` VALUES ('65', '0.138\"', 'Head Diameter ');
INSERT INTO `filters` VALUES ('66', '0.044\"', 'Head Height ');
INSERT INTO `filters` VALUES ('67', '82Â°', 'Countersink Angle');
INSERT INTO `filters` VALUES ('68', '1/32 \"', 'Drive Size');
INSERT INTO `filters` VALUES ('69', 'Rockwell C32', 'Hardness');
INSERT INTO `filters` VALUES ('70', '120,000 psi', 'Tensile Strength');
INSERT INTO `filters` VALUES ('71', 'Flat', 'Head Type');
INSERT INTO `filters` VALUES ('72', 'ASTM F835', 'Specifications Met');
INSERT INTO `filters` VALUES ('73', '3/8 \"', 'Length ');
INSERT INTO `filters` VALUES ('74', '7/16 \"', 'Length ');
INSERT INTO `filters` VALUES ('75', '1/2 \"', 'Length ');
INSERT INTO `filters` VALUES ('76', '9/16 \"', 'Length ');
INSERT INTO `filters` VALUES ('77', '5/8 \"', 'Length ');
INSERT INTO `filters` VALUES ('78', '3/4 \"', 'Length ');
INSERT INTO `filters` VALUES ('79', '7/8 \"', 'Length ');
INSERT INTO `filters` VALUES ('80', '1\"', 'Length ');
INSERT INTO `filters` VALUES ('81', '1 1/8 \"', 'Length ');
INSERT INTO `filters` VALUES ('82', '1 1/4 \"', 'Length ');
INSERT INTO `filters` VALUES ('83', '1 1/2 \"', 'Length ');
INSERT INTO `filters` VALUES ('84', 'Partially Threaded', 'Threading');
INSERT INTO `filters` VALUES ('85', '1/2 \"', 'Minimum Thread Length ');
INSERT INTO `filters` VALUES ('86', '1-64', 'Thread Size');
INSERT INTO `filters` VALUES ('87', '0.118\"', 'Head Diameter ');
INSERT INTO `filters` VALUES ('88', '0.073\"', 'Head Height ');
INSERT INTO `filters` VALUES ('89', '1/16 \"', 'Drive Size');
INSERT INTO `filters` VALUES ('90', '0.073\"', 'Screw Size Decimal Equivalent');
INSERT INTO `filters` VALUES ('91', 'UNC', 'Thread Type');
INSERT INTO `filters` VALUES ('92', '3/4 \"', 'Minimum Thread Length ');
INSERT INTO `filters` VALUES ('93', '1-72', 'Thread Size');
INSERT INTO `filters` VALUES ('94', '2-56', 'Thread Size');
INSERT INTO `filters` VALUES ('95', '0.14\"', 'Head Diameter ');
INSERT INTO `filters` VALUES ('96', '0.086\"', 'Head Height ');
INSERT INTO `filters` VALUES ('97', '5/64 \"', 'Drive Size');
INSERT INTO `filters` VALUES ('98', '0.086\"', 'Screw Size Decimal Equivalent');
INSERT INTO `filters` VALUES ('99', '5/8 \"', 'Minimum Thread Length ');
INSERT INTO `filters` VALUES ('100', '1 3/8 \"', 'Length ');
INSERT INTO `filters` VALUES ('101', '1 3/4 \"', 'Length ');
INSERT INTO `filters` VALUES ('102', '2\"', 'Length ');
INSERT INTO `filters` VALUES ('103', '2 1/2 \"', 'Length ');
INSERT INTO `filters` VALUES ('104', 'Zinc-Plated Alloy Steel', 'Material');
INSERT INTO `filters` VALUES ('105', '2-64', 'Thread Size');
INSERT INTO `filters` VALUES ('106', '3-48', 'Thread Size');
INSERT INTO `filters` VALUES ('107', '0.161\"', 'Head Diameter ');
INSERT INTO `filters` VALUES ('108', '0.099\"', 'Head Height ');
INSERT INTO `filters` VALUES ('109', '0.099\"', 'Screw Size Decimal Equivalent');
INSERT INTO `filters` VALUES ('110', '3-56', 'Thread Size');
INSERT INTO `filters` VALUES ('111', '4-40', 'Thread Size');
INSERT INTO `filters` VALUES ('112', '0.183\"', 'Head Diameter ');
INSERT INTO `filters` VALUES ('113', '0.112\"', 'Head Height ');
INSERT INTO `filters` VALUES ('114', '3/32 \"', 'Drive Size');
INSERT INTO `filters` VALUES ('115', '0.112\"', 'Screw Size Decimal Equivalent');
INSERT INTO `filters` VALUES ('116', '10-24', 'Thread Size');
INSERT INTO `filters` VALUES ('117', '2 3/4 \"', 'Length ');
INSERT INTO `filters` VALUES ('118', '7/8 \"', 'Minimum Thread Length ');
INSERT INTO `filters` VALUES ('119', '0.312\"', 'Head Diameter ');
INSERT INTO `filters` VALUES ('120', '0.19\"', 'Head Height ');
INSERT INTO `filters` VALUES ('121', '5/32 \"', 'Drive Size');
INSERT INTO `filters` VALUES ('122', '0.190\"', 'Screw Size Decimal Equivalent');
INSERT INTO `filters` VALUES ('123', '3\"', 'Length ');
INSERT INTO `filters` VALUES ('124', '3 1/4 \"', 'Length ');
INSERT INTO `filters` VALUES ('125', '3 1/2 \"', 'Length ');
INSERT INTO `filters` VALUES ('126', '3 3/4 \"', 'Length ');
INSERT INTO `filters` VALUES ('127', '4\"', 'Length ');
INSERT INTO `filters` VALUES ('128', '4 1/4 \"', 'Length ');
INSERT INTO `filters` VALUES ('129', '4 3/8 \"', 'Length ');
INSERT INTO `filters` VALUES ('130', '4 1/2 \"', 'Length ');
INSERT INTO `filters` VALUES ('131', '4 3/4 \"', 'Length ');
INSERT INTO `filters` VALUES ('132', '5\"', 'Length ');
INSERT INTO `filters` VALUES ('133', '5 1/4 \"', 'Length ');
INSERT INTO `filters` VALUES ('134', '5 1/2 \"', 'Length ');
INSERT INTO `filters` VALUES ('135', '6\"', 'Length ');
INSERT INTO `filters` VALUES ('136', '6 1/2 \"', 'Length ');
INSERT INTO `filters` VALUES ('137', '6 3/4 \"', 'Length ');
INSERT INTO `filters` VALUES ('138', '7 1/2 \"', 'Length ');
INSERT INTO `filters` VALUES ('139', '8\"', 'Length ');
INSERT INTO `filters` VALUES ('140', '1\"', 'Minimum Thread Length ');
INSERT INTO `filters` VALUES ('141', '2 1/4 \"', 'Length ');
INSERT INTO `filters` VALUES ('142', 'Zinc-Aluminum-Coated Alloy Steel', 'Material');
INSERT INTO `filters` VALUES ('143', 'ASME B18.3, ASTM A574, ASTM B117', 'Specifications Met');
INSERT INTO `filters` VALUES ('144', '10-32', 'Thread Size');
INSERT INTO `filters` VALUES ('145', '1 5/8 \"', 'Length ');
INSERT INTO `filters` VALUES ('146', '1 7/8 \"', 'Length ');

-- ----------------------------
-- Table structure for products
-- ----------------------------
DROP TABLE IF EXISTS `products`;
CREATE TABLE `products` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `price` varchar(255) DEFAULT NULL,
  `description` text,
  `categories` varchar(255) DEFAULT NULL,
  `filters` varchar(255) DEFAULT NULL,
  `image` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_prod_name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of products
-- ----------------------------
INSERT INTO `products` VALUES ('1', 'Black-Oxide  Alloy Steel Socket Head Screw', '$13.09 per pack of 50', 'These screws are made from an alloy steel thats  stronger than Grade 8 steel.  Length is measured from under the head. Black-oxide steel screws are mildly corrosion resistant in dry environments. ', '701', '48,49,21,50,51,52,25,27,28,53,54,55,56,32,33,34,35,57,7,8,58,59,60,61,62,63,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,30,92,93,94,95,96,97,98,99,100,101,102,103,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124', '/mvA/Contents/gfx/ImageCache/912/91251A051p1-b01-digital@1x_635926769087129847.png?ver=ImageNotFound');
INSERT INTO `products` VALUES ('3', 'Zinc-Plated  Alloy Steel Socket Head Screw', '$10.61 per pack of 50', 'These screws are made from an alloy steel thats  stronger than Grade 8 steel.  Length is measured from under the head. Zinc-plated steel screws are more corrosion resistant than black-oxide screws for use in wet environments. ', '701', '94,61,21,95,96,97,104,27,28,98,91,30,56,32,33,34,35,57,7,8,62,63,75,77,78,80,84,99,116,119,120,121,122,73,79,81,118,82,92,83,140,101,102,141,103,117,123,125', '/mvA/Contents/gfx/ImageCache/901/90128A040p1-b01-digitall@1x_636050900782499137.png?ver=ImageNotFound');
INSERT INTO `products` VALUES ('4', 'Zinc-Aluminum-Coated  Alloy Steel Socket Head Screw', '$8.11 per pack of 25', 'These screws are made from an alloy steel thats  stronger than Grade 8 steel.  Length is measured from under the head. Zinc-aluminum-coated steel screws are 40 times as corrosion resistant as zinc-plated screws and are also known as Magni-coated screws.  They withstand 1, 000 hours of salt spray per ASTM B117. ', '701', '116,62,21,119,120,121,142,27,28,122,91,30,56,32,33,34,35,143,7,8,73,77,78,79,80,82,84,118,83,101,102,141,103', '/mvA/Contents/gfx/ImageCache/912/91274A096p1-b01-digitall@1x_636051738129248397.png?ver=ImageNotFound');
